Kitware/react-vtk-js

package.json, src/core/View.js
Allows to set the focal point as center of rotation option for the rotate manipulator in the interactorSettings object.
=> Expose focal point as center of rotation option

package.json
Is there any reason why the vtk.js version is fixed to a single release? Could this library specify a range to make it easier to use it with other vtk.js logic?
This seems to fix #15
=> allow broader range of vtk.js versions

src/core/ShareDataSet.js
The trivial producer listener should be removed when the component is unmounted.
@WillCMcC @agirault
=> fix(ShareDataSet): Stop data listener on unmount

src/core/Reader.js
Add `options` property to the Reader, which will be passed to STLReader(or other vtk.js readers). The main reason is to be able to pass `progressCallback` and display progress in UI.
~However there is also bug related to progressCallback on vtk.js side. I submitted [PR with fix](https://github.com/Kitware/vtk-js/pull/2007), so if you want to check scenario with progressCallback - it will not work until aforementioned PR merged.~
The second commit make it work without the changes to the vtk.js reader.
=> fix(Reader): Add options property to Reader

src/core/View.js
=> fix: don’t attempt to call prop.get() when prop is nullish

src/core/View.js
I'm trying to understand why these changes aren't working, as soon I set a pointerSize larger than 0 picking stops working 🤔
=> feat(View): pointerSize property

package.json
Having vtk.js as a dependency makes it extremely difficult to avoid double versions of the same library if vtk.js is also listed as dependency of the project itself.
Just like it happens with React, I think vtk.js should be a peerDependency so that the consumers can better control it.
Keep it mind 99% of the users using this library are likely going to also import from vtk.js directly to access utility modules and such, so they will need to add a vtk.js version to their package.json too.
=> fix: mark vtk.js as peer dependency

package-lock.json, package.json, src/core/View.js
Having access to the browser events is useful if you need to perform logic with the mouse position, modifier keys, etc.
This change should preserve backwards compatibility with the existing interface by adding a second argument to the event callbacks.
=> feat(View): forward browser events

src/core/View.js
When we switch between different mouse adaptors programmatically (directly interacting with the `style` and `view` instances) we often get the error:
```
cannot get getViewMatrix of undefined
```
This happens on the CubeAxesActor instance, and only happens if `showCubeAxes` prop is not set to `true`.
This change prevents the error from happening.
=> fix(View): don’t throw `cannot get getViewMatrix of undefined` error when showCubeAxes is set to false

src/core/SliceRepresentation.js
There was an issue in SliceRepresenation.js: when providing 0 for i,j,k,x,y, or z slice, a falsy check would prevent the mapper from updating the corresponding slice. I've updating to a nullish check with `!=` because that is the convention I am used to but can update if need be!
=> (Fix) Change falsy checks on slice value to nullish checks

package.json, src/core/Geometry2DRepresentation.js, src/core/index.js, src/index.js, usage/Geometry/PolyDataViewer.js
Depends on https://github.com/Kitware/vtk-js/pull/2179
=> feat(Rendering): Introduce Geometry2DRepresentation

src/core/View.js
**This PR adds orientation axes in the view.**
The property `showOrientationAxes` was added in the class `View` to set the visibility of the orientation axes.
=> Add orientation axes in the view

src/core/View.js
Set the default value of showOrientationAxes flag to false.
Applications that want to use the default Axes should
explicitly turn it ON.
=> fix(View): set default showOrientationAxes false

src/core/View.js, src/core/ViewContainer.js
Fixes some multi-view interaction bugs.
=> Fix interaction

src/core/MultiViewRoot.js, src/core/View.js, src/core/ViewContainer.js
MultiViewRoot should manage the resize listener for descendants in order to
batch render calls efficiently.
=> fix(MultiViewRoot): consolidate renders on resize

.github/workflows/gh-pages.yml
Publishing to docs seems to be [failing](https://github.com/Kitware/react-vtk-js/runs/5452561422?check_suite_focus=true), seems like last push to `gh-pages` branch was ~10 months so maybe the creds were changed.
This PR changes current workflow to publish usage docs from using `gh-pages` command line to use [github-pages-action](https://github.com/marketplace/actions/github-pages-action) action. 
This uses `GITHUB_TOKEN` provided by all github actions instead of custom auth.
Note: Haven't tested if it works, and not sure if instructions [here](https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-first-deployment-with-github_token) would need to be followed.
=> docs: fix publish to gh-pages

package-lock.json, package.json, src/core/View.js
Reverts setting mousedown on capture. This is related to https://github.com/Kitware/vtk-js/pull/2462 in that preventDefault is no longer invoked by default, so this change (which didn't fix anything anyways) can be reverted.
TODO: update the vtk.js version required, as to avoid mousedown breakage.
=> fix(View): revert mousedown capture

src/core/View.js
We don't need to initialize cubeAxesActor if the showCubeAxes prop is false
=> fix: do not initialize cubeAxesActor if not required

src/core/DataArray.js
Pass range information to DataArray externally if available, to avoid multiple calls to computeRange, since this can be a performance penalty if the image data is very large.
Example shown below:
```js
<DataArray
registration="setScalars"
values={dataArray}
range={{ min: range[0], max: range[1] }}
/>
```
=> fix(DataArray): add range info to DataArray

src/core/View.js
Issue: focalPoint is reset due to resetCamera call for each position update.
I added focalPoint as prop, and setting it after resetCamera, to retain focalpoint.
[line 465
`if (previous) {
this.resetCamera();
}`](https://github.com/Kitware/react-vtk-js/blob/master/src/core/View.js#L465)
=> Added focalPoint as prop and setting on update

src/core/DataArray.js
This fix should allow the correct unmounting of DataArrays and their removal from the fields context.
Linked to #76
=> use Name instead of array for removal

src/core/View.js
This optimization avoids the need for the browser to run a Layout event in case we don't need the result of `this.getScreenEventPositionFor`.
Before this fix, we would always run the `getBoundingClientRect` and then discard its result in the `this.hover` handler.
=> perf: don’t trigger layout event if hover is not in picking modes

package-lock.json, package.json, usage/package-lock.json
Getting "Uncaught TypeError: pako__WEBPACK_IMPORTED_MODULE_1__.default.deflate is not a function" when attempting to use XMLWriter. Bumping should fix this.
=> fix(XMLWriter): Bunp vtk.js version to fix crash when using XMLWriter
